version: "3"
volumes:
  headway_graphhopper_vol:
    external: true
services:
  mbtileserver:
    image: headway_tileserver
    environment:
      PORT: 8000
  photon:
    image: headway_photon
  nominatim:
    image: headway_nominatim
  graphhopper:
    image: headway_graphhopper
    volumes:
    - "headway_graphhopper_vol:/graph_volume"
  nginx:
    image: headway_nginx
    ports:
    - "8080:8080"
